WIP - test installer
geolessel/vox pull request #36
Opened 2023-09-11 02:15 UTC by Parker-Bartlett

related to https://github.com/geolessel/vox/issues/31

Starting to add tests to the installer, just pushing up as WIP for visibility. Hoping to add more tests in the coming days.

Mostly follows the testing strategy used in the phoenix installer.

2023-09-13 12:58 UTC, geolessel commented
Oooooh, thank you so much! FWIW, I don't mind little PRs that chunk out the work. Even a PR that tests one little piece of functionality would be big enough to merge in IMO.

Let me know when you are comfortable with where this PR is at and we'll go from there.

2023-09-16 23:50 UTC, Parker-Bartlett commented
@geolessel I'm all for keeping PRs small 😄 

It should be ready to look over, let me know if there's anything I can update.

By the way, the last commit is adding the installer tests to CI, I can't validate that it works myself. I should be able to tell once the workflow runs on this PR.

2023-09-17 01:51 UTC, geolessel requested changes
These are fantastic! I have a style change request and one more thing that needs to be done.

Could you loosen the Elixir version restriction in the installer's `mix.exs` file to `1.14`? That way it'll work with the testing workflow matrix versions.

2023-09-17 01:51 UTC, geolessel commented on installer/test/mix_helper.exs
> +    len |> :crypto.strong_rand_bytes() |> Base.encode64() |> binary_part(0, len)
Simple style pickiness I suppose but for piped logic I prefer one pipe per line. Mind changing it?
```suggestion
    len
    |> :crypto.strong_rand_bytes()
    |> Base.encode64()
    |> binary_part(0, len)
```

2023-09-17 02:30 UTC, geolessel commented
@Parker-Bartlett Getting closer! It looks like we need to `mix deps.get` for the installer as well before we can test. Makes sense! 😆

2023-09-17 02:45 UTC, geolessel commented
@Parker-Bartlett 🤔 and/or make `ex_doc` a `:dev`-only dep.

```elixir
defp deps do
  [
    {:ex_doc, "~> 0.30.6", only: :dev, runtime: false}
  ]
end
```

2023-09-17 03:27 UTC, Parker-Bartlett commented
Fingers crossed this is the one! And thanks for running CI on these 😆

2023-09-17 13:57 UTC, geolessel approved these changes
That did it! Thanks so much for these. I really appreciate it.

2023-09-17 13:57 UTC, merged